@extends('layouts.website')

@section('main')
	<div class="container mx-auto space-y-6 *:mx-3">
		<section>
			<div class="relative mx-auto w-full gap-8 pt-14 pb-20 space-y-8">
				<div class="flex flex-col items-center text-center space-y-3">
					<flux:button icon="question-mark-circle" size="sm" class="rounded-full! pointer-events-none">Legal</flux:button>
					<h1 class="pb-3 font-bold text-[32px] lg:text-5xl">
						<span>Privacy Policy</span>
					</h1>
					<p class="max-w-md text-base text-zinc-500 lg:max-w-2xl">
						Learn how we collect, use, and protect your personal information in our privacy policy.
					</p>
				</div>
			</div>
			<div class="rounded-2xl border border-zinc-300 bg-white p-10 shadow-lg">
				<div class="prose max-w-none">
					<div class="flex justify-end items-center gap-2">
						<span class="text-xs">Effective Date</span>
						<flux:badge color="zinc" class="font-mono font-bold!">12 02 2025</flux:badge>
					</div>

					<h2>Privacy Policy Introduction</h2>

					<p>Welcome to ReplyElf (the "Site"), operated by IframeAI ("we", "us", and/or "our"). IframeAI provides a platform for managing and enhancing web pages (the "Services"). We value your privacy and are dedicated to protecting your personal data. This Privacy Policy explains how we collect, use, and disclose your personal data on our platform.</p>
					<p>By using our Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined, terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.</p>

					<div>
						<div class="flex items-center gap-3">
							<flux:badge color="zinc" class="font-mono font-bold!">01</flux:badge>
							<span class="p-0 font-semibold text-md">Definitions</span>
						</div>
					</div>
					<p class="text-zinc-500">Below is a list of definitions for the terms used in this Privacy Policy:</p>

					<table>
						<thead>
							<tr>
								<th>Term</th>
								<th>Definition</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>Service</td>
								<td>The IframeAI.com website and related web applications operated by IframeAI.</td>
							</tr>
							<tr>
								<td>Personal Data</td>
								<td>Data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</td>
							</tr>
							<tr>
								<td>Usage Data</td>
								<td>Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (e.g., duration of a page visit).</td>
							</tr>
							<tr>
								<td>Cookies</td>
								<td>Small files stored on your device (computer or mobile device).</td>
							</tr>
							<tr>
								<td>Data Controller</td>
								<td>A person or entity that determines the purposes and means of processing personal data. For the purpose of this Privacy Policy, we are the Data Controller of your data.</td>
							</tr>
							<tr>
								<td>Data Processors (or Service Providers)</td>
								<td>Any natural or legal person who processes the data on behalf of the Data Controller.</td>
							</tr>
							<tr>
								<td>Data Subject</td>
								<td>Any living individual who is the subject of Personal Data.</td>
							</tr>
							<tr>
								<td>User</td>
								<td>The individual using our Service, who corresponds to the Data Subject.</td>
							</tr>
						</tbody>
					</table>

					<div>
						<div class="flex items-center gap-3">
							<flux:badge color="zinc" class="font-mono font-bold!">02</flux:badge>
							<span class="p-0 font-semibold text-md">Information Collection and Use</span>
						</div>
					</div>

					<p>We collect different types of information to provide and improve our Service.</p>

					<div>
						<div class="flex items-center gap-3">
							<flux:badge color="zinc" class="font-mono font-bold!">03</flux:badge>
							<span class="p-0 font-semibold text-md">Use of Data</span>
						</div>
					</div>
					<p>We use the collected data for various purposes:

						To provide and maintain our Service

						To notify you about changes to our Service

						To provide customer support

						To analyze and improve our Service

						To monitor usage and detect security threats

						To comply with legal obligations

						We do not sell your data to third parties.</p>

					<div>
						<div class="flex items-center gap-3">
							<flux:badge color="zinc" class="font-mono font-bold!">04</flux:badge>
							<span class="p-0 font-semibold text-md">Retention of Data</span>
						</div>
					</div>
					<p>We retain your Personal Data only as long as necessary for the purposes set out in this Privacy Policy. Usage Data is generally retained for a shorter period, except when required for security or legal compliance.</p>


					<div>
						<div class="flex items-center gap-3">
							<flux:badge color="zinc" class="font-mono font-bold!">05</flux:badge>
							<span class="p-0 font-semibold text-md">Transfer of Data</span>
						</div>
					</div>
					<p>Your data is stored on our own servers, which may be located in Romania or other jurisdictions where we operate. We take all necessary measures to ensure that your data remains protected.</p>

					<div>
						<div class="flex items-center gap-3">
							<flux:badge color="zinc" class="font-mono font-bold!">06</flux:badge>
							<span class="p-0 font-semibold text-md">Disclosure of Data</span>
						</div>
					</div>
					<p>We may disclose your Personal Data under the following circumstances:</p>
					Legal Requirements: If required by law or in response to valid requests by authorities.

					Business Transactions: If we are involved in a merger, acquisition, or asset sale.

					Security and Compliance: To protect the rights, property, or safety of our company, customers, or others.

					<div>
						<div class="flex items-center gap-3">
							<flux:badge color="zinc" class="font-mono font-bold!">07</flux:badge>
							<span class="p-0 font-semibold text-md">Security of Data</span>
						</div>
					</div>
					<p>We implement commercially reasonable security measures to protect your Personal Data. However, no method of transmission over the Internet or electronic storage is 100% secure.</p>

					<div>
						<div class="flex items-center gap-3">
							<flux:badge color="zinc" class="font-mono font-bold!">08</flux:badge>
							<span class="p-0 font-semibold text-md">Your GDPR Rights</span>
						</div>
					</div>
					If you are in the European Union (EU) or European Economic Area (EEA), you have rights under the General Data Protection Regulation (GDPR), including:

					The right to access, update, or delete your data

					The right to object to processing

					The right to data portability

					The right to withdraw consent at any time

					To exercise these rights, contact us at support@ReplyElf.com.

					<div>
						<div class="flex items-center gap-3">
							<flux:badge color="zinc" class="font-mono font-bold!">09</flux:badge>
							<span class="p-0 font-semibold text-md">Children's Privacy</span>
						</div>
					</div>
					<p>Our Service is not intended for individuals under the age of 18. We do not knowingly collect data from minors. If you believe a minor has provided us with Personal Data, contact us for removal.</p>
					<div>
						<div class="flex items-center gap-3">
							<flux:badge color="zinc" class="font-mono font-bold!">10</flux:badge>
							<span class="p-0 font-semibold text-md">Changes to This Privacy Policy</span>
						</div>
					</div>
					<p>We may update this Privacy Policy periodically. We will notify you of changes by updating the "Effective Date" at the top of this page. We encourage you to review this policy regularly.</p>
					<div>
						<div class="flex items-center gap-3">
							<flux:badge color="zinc" class="font-mono font-bold!">11</flux:badge>
							<span class="p-0 font-semibold text-md">Contact Us</span>
						</div>
					</div>

					<p></p>
				</div>
			</div>
		</section>
	</div>
@endsection